# Generated by Django 4.2.11 on 2024-04-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
